import image1 from "../../../Image/photo/Other/bin-truck.png";
import image2 from "../../../Image/photo/Other/germagic.jpg";
import image3 from "../../../Image/photo/Other/scissor-lift.jpeg";
import image4 from "../../../Image/photo/Other/scissor-trailer.png";

const ImageData=[
    {photo:image1,title:"Bin Truck",short_desc:"Bin Truck",description:"Aliqua reprehenderit anim culpa aute excepteur dolor voluptate laboris deserunt et eiusmod cupidatat magna. Sit incididunt eu enim nisi ullamco incididunt. Amet duis commodo quis ex dolore. Laboris incididunt est velit duis dolor. Magna ullamco enim mollit enim et occaecat excepteur aute reprehenderit. Laboris eu laboris tempor non cupidatat ut pariatur reprehenderit veniam ex. Nulla enim fugiat qui quis anim cupidatat ipsum veniam dolore nulla do.",type:["a","b","c"]},
    {photo:image2,title:"Germagic",short_desc:"Germagic disinfectant",description:"Aute consequat nostrud magna et velit dolor. Laboris excepteur sint adipisicing mollit nulla quis. Cupidatat id ea ea nulla voluptate nostrud ut quis tempor ea dolore exercitation ullamco. Sint reprehenderit nisi sunt nulla reprehenderit sunt. Adipisicing deserunt qui Lorem reprehenderit enim. Veniam mollit nulla anim consequat Lorem sit magna eiusmod aliquip labore officia consectetur commodo consequat. Non et velit velit qui irure sint ea voluptate.",type:["a","b","c"]},
    {photo:image3,title:"Scissor Lift",short_desc:"Scissor lift",description:"Et pariatur amet elit ea pariatur ad reprehenderit enim exercitation tempor culpa occaecat minim. Commodo minim amet ad deserunt mollit nisi dolore reprehenderit. Mollit aliquip sint ut esse enim labore sint veniam. Nostrud pariatur consectetur esse culpa tempor deserunt cillum esse Lorem Lorem ex. Labore quis laboris dolor eu anim ipsum ullamco ut esse velit duis. Veniam amet incididunt veniam id deserunt irure officia reprehenderit exercitation esse enim magna est laborum.",type:["a","b","c"]},
    {photo:image4,title:"Scissor Trailer",short_desc:"Scissor trailer",description:"Aliqua sint cillum velit ut et minim ipsum irure tempor eu ut quis in ex. Eiusmod id sunt est laborum dolore reprehenderit aute in commodo esse. Aliquip laboris voluptate excepteur aliqua minim sit aliqua amet do Lorem excepteur commodo Lorem ad. Culpa consectetur culpa ullamco et fugiat ad voluptate consectetur ipsum. Adipisicing elit velit cillum enim laboris commodo commodo consectetur ad nulla. Reprehenderit qui irure ipsum aliqua aliquip.",type:["a","b","c"]}]
export default ImageData;